language: python
dist: xenial
sudo: required
python:
- '3.6'
- '3.7'
cache: pip
install:
- pip install -r requirements-test.txt
script:
- flake8 --max-line-length 100 **/*.py
deploy:
  provider: pypi
  user: __token__
  distributions: sdist bdist_wheel
  skip_existing: true
  on:
    tags: true
  password:
    secure: MfG5bquMgFy/QOdSYMjOjT+b8YVdIxf0SEzm+cUNl5CVNZKS+E8mJE6pUHKXubwDPkwq+wIGzIHqmuRo1JJEf0/GBHkGXomUQY/VbqCKwPwFMsBGMVtefAk9CXcN5Ry0UreXX/vehPGAcoKLzxK99FVnTpZX4thnFCL7Ll0IrwqXHz0Vl15O+4aVPqk4OXA152yYsQeyQP/y+oCJsFyUt/H1ZZvXVvkBEsAxWmvKIMliM1Xp+4swd23JI2CJKEXCs5Ckhe1vsG5gKFuK3jRx+lLoJBJLsZ4Zx2oi9FN5jE8mmY1VUKnJ6D+y+4dHOvBBP9jPFtQ/ky3f1qEcdBQ0ThTGmKvF+lAhEue551IJE74OlAeXLGv0nU675Kwxz06DY6SwIDk7y+Uj8iEUYmR0RgxZWC/py4KCXEssLy0UFgW++EN/0PbsDl4u1+z5Y6h9aswFSMv9BSTreI6cCz+kQNYuhJUs9wZiYI5OXPiOuX7CPbMnbHD8XeNUtXufMC5Xg9qrhWIm/eO82ev2pzzwBkH6CFqyRX9XQJLEZKvi0xLayqEVxtnTem2EgNkg7048eli9X+BRlg8LGrEs+ciVTy1084AJ76KvTjuQsUNh0s4+WYmL8mlfjdp/ADmwEYe/ngrTwJ2Lh636n0R5LOOdqoP0Fd4HoPAlLuCQG/fIfyo=
