name: 🕵️ Test suite

on:
  push:
  pull_request:
    types: ["opened", "synchronize", "reopened"]
jobs:
  flake8:
    name: flake8
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - name: Checkout to master
        uses: actions/checkout@v4

      - name: Setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
          architecture: 'x64'

      - name: flake8 Lint
        uses: reviewdog/action-flake8@v3
        with:
          filter_mode: nofilter
          github_token: ${{ secrets.GITHUB_TOKEN }}

  platform:
    name: 💻 Platform-${{ matrix.os }}
    needs: [ flake8 ]
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    steps:
      - name: Checkout to master
        uses: actions/checkout@v4

      - name: Setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
          architecture: 'x64'

      - name: Development setup on ${{ matrix.os }}
        run: |
          python -m pip install pip --upgrade
          pip install -e .
          python -c "from ocviapy import get_associated_pods, get_routes, get_json"

  package:
    name: ⚙️ Build and Verify Package
    runs-on: ubuntu-latest
    needs: [ flake8 ]
    steps:
      - name: Checkout to master
        uses: actions/checkout@v4

      - name: Setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
          architecture: 'x64'

      - name: Twine checks
        run: |
          python -m pip install pip twine setuptools wheel --upgrade
          python setup.py sdist bdist_wheel
          ls -l dist
          python -m twine check dist/*
